// Dave Johnson
// 09/19/12
// Visual Frameworks 1209
// Assignment 4

var json = {
    "Order1": {
        "firstname": ["First Name:", "Joe"],
        "lastname": ["Last Name:", "Soreaka"],
        "address": ["Address:", "353 Nomei St."],
        "city": ["City:", "Arcadia"],
        "select": ["State:", "FL"],
        "phnumber": ["Phone Number:", "(184)943-3983"],
        "crust": ["Crust:", "No Crust"],
        "xtracheese": ["Extra Cheese", "Yes"],
        "pepperoni": ["Pepperoni:", "None"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "Yes"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "Yes"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "Yes"],
        "spnch": ["Spinach:", "None"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "No"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "Yes"],
        "qty": ["Qauntity:", "19"],
        "method": ["Method:", "Delivery"],
        "date": ["Date:", "2012-09-30"],
        "instruct": ["Special Instructions:", "ASAP"]
    },
    "Order2": {
        "firstname": ["First Name:", "Tammy"],
        "lastname": ["Last Name:", "Jeafilo"],
        "address": ["Address:", "94 Rocky Road Ave."],
        "city": ["City:", "Denver"],
        "select": ["State:", "CO"],
        "phnumber": ["Phone Number:", "(974)389-1937"],
        "crust": ["Crust:", "Thin Crust"],
        "xtracheese": ["Extra Cheese", "Yes"],
        "pepperoni": ["Pepperoni:", "Yes"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "Yes"],
        "onion": ["Onion:", "None"],
        "grnpepper": ["Green Pepper:", "None"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "Yes"],
        "spnch": ["Spinach:", "None"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "No"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "Yes"],
        "qty": ["Qauntity:", "7"],
        "method": ["Method:", "Pick Up"],
        "date": ["Date:", "2012-09-28"],
        "instruct": ["Special Instructions:", "Tomorrow is fine."]
    },
    "Order3": {
        "firstname": ["First Name:", "Jeanette"],
        "lastname": ["Last Name:", "Cerodas"],
        "address": ["Address:", "94814 Savvy Port Dr."],
        "city": ["City:", "Rangeport"],
        "select": ["State:", "IA"],
        "phnumber": ["Phone Number:", "(892)310-9037"],
        "crust": ["Crust:", "Deep Dish"],
        "xtracheese": ["Extra Cheese", "None"],
        "pepperoni": ["Pepperoni:", "None"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "Yes"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "None"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "None"],
        "spnch": ["Spinach:", "None"],
        "alfredo": ["Alfredo Sauce:", "Yes"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "Yes"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "None"],
        "qty": ["Qauntity:", "3"],
        "method": ["Method:", "Delivery"],
        "date": ["Date:", "2012-09-28"],
        "instruct": ["Special Instructions:", "Whenever."]
    },
    "Order4": {
        "firstname": ["First Name:", "Rick"],
        "lastname": ["Last Name:", "Ottomen"],
        "address": ["Address:", "1234 Wild Road Dr."],
        "city": ["City:", "Novi"],
        "select": ["State:", "MI"],
        "phnumber": ["Phone Number:", "(345)234-3596"],
        "crust": ["Crust:", "Stuffed Crust"],
        "xtracheese": ["Extra Cheese", "Yes"],
        "pepperoni": ["Pepperoni:", "None"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "Yes"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "None"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "Yes"],
        "spnch": ["Spinach:", "None"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "Yes"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "None"],
        "qty": ["Qauntity:", "16"],
        "method": ["Method:", "Pick Up"],
        "date": ["Date:", "2012-09-28"],
        "instruct": ["Special Instructions:", "I want it now!"]
    },
    "Order5": {
        "firstname": ["First Name:", "Joseph"],
        "lastname": ["Last Name:", "Eiderman"],
        "address": ["Address:", "33 Oak Wood Blvd."],
        "city": ["City:", "San Antonio"],
        "select": ["State:", "TX"],
        "phnumber": ["Phone Number:", "(319)983-7583"],
        "crust": ["Crust:", "No Crust"],
        "xtracheese": ["Extra Cheese", "Yes"],
        "pepperoni": ["Pepperoni:", "None"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "Yes"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "None"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "Yes"],
        "spnch": ["Spinach:", "Yes"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "None"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "None"],
        "qty": ["Qauntity:", "3"],
        "method": ["Method:", "Delivery"],
        "date": ["Date:", "2012-09-28"],
        "instruct": ["Special Instructions:", "Extra Extra Cheese Please!"]
    },
    "Order6": {
        "firstname": ["First Name:", "Dawn"],
        "lastname": ["Last Name:", "Easley-Myer"],
        "address": ["Address:", "390 Ocollus Rd."],
        "city": ["City:", "Las Vegas"],
        "select": ["State:", "NV"],
        "phnumber": ["Phone Number:", "(393)783-8764"],
        "crust": ["Crust:", "Stuffed Crust"],
        "xtracheese": ["Extra Cheese", "Yes"],
        "pepperoni": ["Pepperoni:", "None"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "Yes"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "None"],
        "mush": ["Mushrooms:", "Yes"],
        "bbq": ["Barbeque:", "Yes"],
        "spnch": ["Spinach:", "Yes"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "None"],
        "rnch": ["Ranch:", "None"],
        "blch": ["Blue Cheese:", "None"],
        "qty": ["Qauntity:", "1"],
        "method": ["Method:", "Pick Up"],
        "date": ["Date:", "2012-09-28"],
        "instruct": ["Special Instructions:", ""]
    },
        "Order7": {
        "firstname": ["First Name:", "Cameron"],
        "lastname": ["Last Name:", "Ilefios"],
        "address": ["Address:", "12958 Brady Grove Ct."],
        "city": ["City:", "Portland"],
        "select": ["State:", "OR"],
        "phnumber": ["Phone Number:", "(738)651-8721"],
        "crust": ["Crust:", "Thin Crust"],
        "xtracheese": ["Extra Cheese", "None"],
        "pepperoni": ["Pepperoni:", "Yes"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "None"],
        "onion": ["Onion:", "None"],
        "grnpepper": ["Green Pepper:", "None"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "Yes"],
        "spnch": ["Spinach:", "None"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "None"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "Yes"],
        "qty": ["Qauntity:", "8"],
        "method": ["Method:", "Pick Up"],
        "date": ["Date:", "2012-09-31"],
        "instruct": ["Special Instructions:", ""]
    },
    "Order8": {
        "firstname": ["First Name:", "Bob"],
        "lastname": ["Last Name:", "O'Brien"],
        "address": ["Address:", "7831 Beaver Run Blvd."],
        "city": ["City:", "San Diego"],
        "select": ["State:", "CA"],
        "phnumber": ["Phone Number:", "(679)324-1204"],
        "crust": ["Crust:", "Deep Dish"],
        "xtracheese": ["Extra Cheese", "None"],
        "pepperoni": ["Pepperoni:", "Yes"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "Yes"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "None"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "Yes"],
        "spnch": ["Spinach:", "Yes"],
        "alfredo": ["Alfredo Sauce:", "Yes"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "None"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "None"],
        "qty": ["Qauntity:", "8"],
        "method": ["Method:", "Delivery"],
        "date": ["Date:", "2012-09-30"],
        "instruct": ["Special Instructions:", ""]
    },
    "Order9": {
        "firstname": ["First Name:", "JoAnne"],
        "lastname": ["Last Name:", "Clockerway"],
        "address": ["Address:", "9834 Barrel Down Rd."],
        "city": ["City:", "Seymour"],
        "select": ["State:", "IN"],
        "phnumber": ["Phone Number:", "(312)745-3810"],
        "crust": ["Crust:", "Stuffed Crust"],
        "xtracheese": ["Extra Cheese", "Yes"],
        "pepperoni": ["Pepperoni:", "None"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "Yes"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "None"],
        "mush": ["Mushrooms:", "Yes"],
        "bbq": ["Barbeque:", "None"],
        "spnch": ["Spinach:", "None"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "None"],
        "rnch": ["Ranch:", "None"],
        "blch": ["Blue Cheese:", "None"],
        "qty": ["Qauntity:", "3"],
        "method": ["Method:", "Pick Up"],
        "date": ["Date:", "2012-09-29"],
        "instruct": ["Special Instructions:", ""]
    },
    "Order10": {
        "firstname": ["First Name:", "Emily"],
        "lastname": ["Last Name:", "Feikman"],
        "address": ["Address:", "830 Burrowing Forest Blvd."],
        "city": ["City:", "Myrtle Beach"],
        "select": ["State:", "SC"],
        "phnumber": ["Phone Number:", "(847)471-7392"],
        "crust": ["Crust:", "Thin Crust"],
        "xtracheese": ["Extra Cheese", "None"],
        "pepperoni": ["Pepperoni:", "None"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "None"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "Yes"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "Yes"],
        "spnch": ["Spinach:", "Yes"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "None"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "None"],
        "qty": ["Qauntity:", "1"],
        "method": ["Method:", "Pick Up"],
        "date": ["Date:", "2012-09-28"],
        "instruct": ["Special Instructions:", ""]
    },
    "Order11": {
        "firstname": ["First Name:", "Carrie"],
        "lastname": ["Last Name:", "Aleny"],
        "address": ["Address:", "46829 Royalbrook Rd."],
        "city": ["City:", "Beverly Hills"],
        "select": ["State:", "CA"],
        "phnumber": ["Phone Number:", "(763)937-0100"],
        "crust": ["Crust:", "No Crust"],
        "xtracheese": ["Extra Cheese", "None"],
        "pepperoni": ["Pepperoni:", "Yes"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "None"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "Yes"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "None"],
        "spnch": ["Spinach:", "Yes"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "None"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "None"],
        "qty": ["Qauntity:", "20"],
        "method": ["Method:", "Pick Up"],
        "date": ["Date:", "2012-09-29"],
        "instruct": ["Special Instructions:", "Gimme!"]
    },
    "Order12": {
        "firstname": ["First Name:", "Eli"],
        "lastname": ["Last Name:", "Eiphenine"],
        "address": ["Address:", "19205 Brody Ct."],
        "city": ["City:", "Green Bay"],
        "select": ["State:", "WI"],
        "phnumber": ["Phone Number:", "(582)448-3819"],
        "crust": ["Crust:", "No Crust"],
        "xtracheese": ["Extra Cheese", "None"],
        "pepperoni": ["Pepperoni:", "None"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "Yes"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "None"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "Yes"],
        "spnch": ["Spinach:", "None"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "None"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "Yes"],
        "qty": ["Qauntity:", "2"],
        "method": ["Method:", "Delivery"],
        "date": ["Date:", "2012-09-29"],
        "instruct": ["Special Instructions:", "Dunno!"]
    },
    "Order13": {
        "firstname": ["First Name:", "Marina"],
        "lastname": ["Last Name:", "Dutton"],
        "address": ["Address:", "7198 Merrymen Place"],
        "city": ["City:", "Boise"],
        "select": ["State:", "ID"],
        "phnumber": ["Phone Number:", "(912)902-1083"],
        "crust": ["Crust:", "Stuffed Crust"],
        "xtracheese": ["Extra Cheese", "Yes"],
        "pepperoni": ["Pepperoni:", "Yes"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "None"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "None"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "None"],
        "spnch": ["Spinach:", "Yes"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "None"],
        "rnch": ["Ranch:", "None"],
        "blch": ["Blue Cheese:", "Yes"],
        "qty": ["Qauntity:", "8"],
        "method": ["Method:", "Pick Up"],
        "date": ["Date:", "2012-09-29"],
        "instruct": ["Special Instructions:", "Extra Everything!"]
    },
    "Order14": {
        "firstname": ["First Name:", "Mordecai"],
        "lastname": ["Last Name:", "Rigby"],
        "address": ["Address:", "4849 Baer Ct."],
        "city": ["City:", "Cramer"],
        "select": ["State:", "UT"],
        "phnumber": ["Phone Number:", "(486)933-5645"],
        "crust": ["Crust:", "Deep Dish"],
        "xtracheese": ["Extra Cheese", "Yes"],
        "pepperoni": ["Pepperoni:", "Yes"],
        "sausage": ["Sausage:", "Yes"],
        "bacon": ["Bacon:", "Yes"],
        "onion": ["Onion:", "None"],
        "grnpepper": ["Green Pepper:", "None"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "None"],
        "spnch": ["Spinach:", "Yes"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "None"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "None"],
        "qty": ["Qauntity:", "13"],
        "method": ["Method:", "Pick Up"],
        "date": ["Date:", "2012-09-29"],
        "instruct": ["Special Instructions:", "Get 'er done!"]
    },
    "Order15": {
        "firstname": ["First Name:", "Sarah"],
        "lastname": ["Last Name:", "Porkson"],
        "address": ["Address:", "13 Horizon Ave."],
        "city": ["City:", "Miami"],
        "select": ["State:", "FL"],
        "phnumber": ["Phone Number:", "(228)803-3900"],
        "crust": ["Crust:", "Thin Crust"],
        "xtracheese": ["Extra Cheese", "None"],
        "pepperoni": ["Pepperoni:", "Yes"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "None"],
        "onion": ["Onion:", "None"],
        "grnpepper": ["Green Pepper:", "Yes"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "Yes"],
        "spnch": ["Spinach:", "None"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "None"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "None"],
        "qty": ["Qauntity:", "12"],
        "method": ["Method:", "Delivery"],
        "date": ["Date:", "2012-09-28"],
        "instruct": ["Special Instructions:", ""]
    },
    "Order16": {
        "firstname": ["First Name:", "Craig"],
        "lastname": ["Last Name:", "Lazirik"],
        "address": ["Address:", "78 Yorkey Rd."],
        "city": ["City:", "Pittsburgh"],
        "select": ["State:", "PA"],
        "phnumber": ["Phone Number:", "(784)898-1125"],
        "crust": ["Crust:", "Stuffed Crust"],
        "xtracheese": ["Extra Cheese", "Yes"],
        "pepperoni": ["Pepperoni:", "Yes"],
        "sausage": ["Sausage:", "Yes"],
        "bacon": ["Bacon:", "Yes"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "None"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "Yes"],
        "spnch": ["Spinach:", "None"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "None"],
        "bsauce": ["Buffalo Sauce:", "None"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "None"],
        "qty": ["Qauntity:", "8"],
        "method": ["Method:", "Pick Up"],
        "date": ["Date:", "2012-09-27"],
        "instruct": ["Special Instructions:", ""]
    },
    "Order17": {
        "firstname": ["First Name:", "R.L."],
        "lastname": ["Last Name:", "Stein"],
        "address": ["Address:", "1313 Goosebumbs Rd."],
        "city": ["City:", "New York City"],
        "select": ["State:", "NY"],
        "phnumber": ["Phone Number:", "(248)983-8877"],
        "crust": ["Crust:", "Thin Crust"],
        "xtracheese": ["Extra Cheese", "Yes"],
        "pepperoni": ["Pepperoni:", "Yes"],
        "sausage": ["Sausage:", "Yes"],
        "bacon": ["Bacon:", "Yes"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "Yes"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "None"],
        "spnch": ["Spinach:", "None"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "Yes"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "None"],
        "qty": ["Qauntity:", "20"],
        "method": ["Method:", "Pick Up"],
        "date": ["Date:", "2012-09-28"],
        "instruct": ["Special Instructions:", "Extra ranch!"]
    },
    "Order18": {
        "firstname": ["First Name:", "Jake"],
        "lastname": ["Last Name:", "Finn"],
        "address": ["Address:", "7340 Adventure Time Blvd."],
        "city": ["City:", "Los Angelas"],
        "select": ["State:", "CA"],
        "phnumber": ["Phone Number:", "(987)475-7566"],
        "crust": ["Crust:", "Deep Dish"],
        "xtracheese": ["Extra Cheese", "Yes"],
        "pepperoni": ["Pepperoni:", "None"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "None"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "None"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "Yes"],
        "spnch": ["Spinach:", "Yes"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "None"],
        "bsauce": ["Buffalo Sauce:", "Yes"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "None"],
        "qty": ["Qauntity:", "18"],
        "method": ["Method:", "Delivery"],
        "date": ["Date:", "2012-09-26"],
        "instruct": ["Special Instructions:", ""]
    },
    "Order19": {
        "firstname": ["First Name:", "Miranda"],
        "lastname": ["Last Name:", "Codeil"],
        "address": ["Address:", "3104 Buck Run Ave."],
        "city": ["City:", "Chicago"],
        "select": ["State:", "IL"],
        "phnumber": ["Phone Number:", "(877)531-5656"],
        "crust": ["Crust:", "Deep Dish"],
        "xtracheese": ["Extra Cheese", "Yes"],
        "pepperoni": ["Pepperoni:", "None"],
        "sausage": ["Sausage:", "None"],
        "bacon": ["Bacon:", "Yes"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "None"],
        "mush": ["Mushrooms:", "Yes"],
        "bbq": ["Barbeque:", "Yes"],
        "spnch": ["Spinach:", "None"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "None"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "None"],
        "qty": ["Qauntity:", "3"],
        "method": ["Method:", "Delivery"],
        "date": ["Date:", "2012-09-25"],
        "instruct": ["Special Instructions:", ""]
    },
    "Order20": {
        "firstname": ["First Name:", "Allen"],
        "lastname": ["Last Name:", "Ulkefain"],
        "address": ["Address:", "7994 Perrywind Ave."],
        "city": ["City:", "Boston"],
        "select": ["State:", "MA"],
        "phnumber": ["Phone Number:", "(967)227-7663"],
        "crust": ["Crust:", "Thin Crust"],
        "xtracheese": ["Extra Cheese", "None"],
        "pepperoni": ["Pepperoni:", "Yes"],
        "sausage": ["Sausage:", "Yes"],
        "bacon": ["Bacon:", "None"],
        "onion": ["Onion:", "Yes"],
        "grnpepper": ["Green Pepper:", "None"],
        "mush": ["Mushrooms:", "None"],
        "bbq": ["Barbeque:", "Yes"],
        "spnch": ["Spinach:", "None"],
        "alfredo": ["Alfredo Sauce:", "None"],
        "chkn": ["Chicken:", "Yes"],
        "bsauce": ["Buffalo Sauce:", "Yes"],
        "rnch": ["Ranch:", "Yes"],
        "blch": ["Blue Cheese:", "None"],
        "qty": ["Qauntity:", "14"],
        "method": ["Method:", "Pick-Up"],
        "date": ["Date:", "2012-09-28"],
        "instruct": ["Special Instructions:", ""]
    }
}
